"""followers

Revision ID: 749305986b60
Revises: 20833445a738
Create Date: 2023-07-06 21:56:13.359712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749305986b60'
down_revision = '20833445a738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
